hello: 
	echo "hello world"

lab2:
	javac *.java

test1:
	java lab2 test1.asm > out1
	diff -w -B test1.output out1

test2:
	java lab2 test2.asm > out2
	diff -w -B test2.output out2

test3:
	java lab2 test3.asm > out3
	diff -w -B test3.output out3

test4:
	java lab2 test4.asm > out4
	diff -w -B test4.output out4
